# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default='2017-11-22', verbose_name='Date'),
            preserve_default=False,
        ),
    ]
